language: javascript

env:
  global:
    # COVERITY_SCAN_TOKEN
    # ** specific to your project **
    #- secure: ZYK8hYOzsZG85wCJp8oXtw
    - coverity_scan_token: ZYK8hYOzsZG85wCJp8oXtw

addons:
  coverity_scan:

    # GitHub project metadata
    # ** specific to your project **
    project:
      name: asiwen/coverityscanjs_new
      version: 1.0
      description: coverityscanjs

    # Where email notification of build analysis results will be sent
    notification_email: scan_notifications@example.com

    # Commands to prepare for build_command
    # ** likely specific to your build **
    # build_command_prepend: ./configure

    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
    # ** likely specific to your build **
    # build_command: make

    # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: coverity_scan
